default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: lojinha_development

test:
  <<: *default
  adapter: postgresql
  database: lojinha_test
  username: postgres
  password: postgres
  host: 127.0.0.1

production:
  <<: *default
  database: lojinha_production
  username: lojinha
  password: <%= ENV["LOJINHA_DATABASE_PASSWORD"] %>
